

//! Autogenerated weights for `pallet_collective`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.0.0
//! DATE: 2025-08-20, STEPS: `2`, REPEAT: `2`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `blocked.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/datahaven-testnet-runtime/datahaven_testnet_runtime.compact.compressed.wasm
// --pallet
// pallet_collective
// --extrinsic
// 
// --template
// benchmarking/frame-weight-template.hbs
// --output
// runtime/testnet/src/weights/pallet_collective.rs
// --steps
// 2
// --repeat
// 2

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weights for `pallet_collective`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_collective::WeightInfo for WeightInfo<T> {
	/// Storage: `TreasuryCouncil::Members` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Proposals` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Voting` (r:20 w:20)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Prime` (r:0 w:1)
	/// Proof: `TreasuryCouncil::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[0, 9]`.
	/// The range of component `n` is `[0, 9]`.
	/// The range of component `p` is `[0, 20]`.
	fn set_members(m: u32, _n: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (493 ±0) + p * (211 ±0)`
		//  Estimated: `1585 + m * (1028 ±66) + p * (2284 ±29)`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(7_000_000, 1585)
			// Standard Error: 1_078_307
			.saturating_add(Weight::from_parts(4_650_000, 0).saturating_mul(m.into()))
			// Standard Error: 485_238
			.saturating_add(Weight::from_parts(2_092_500, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(p.into())))
			.saturating_add(Weight::from_parts(0, 1028).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 2284).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncil::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[1, 9]`.
	fn execute(b: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `100 + m * (20 ±0)`
		//  Estimated: `1586 + m * (20 ±0)`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(9_309_564, 1586)
			// Standard Error: 893
			.saturating_add(Weight::from_parts(1_467, 0).saturating_mul(b.into()))
			// Standard Error: 114_108
			.saturating_add(Weight::from_parts(187_500, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(Weight::from_parts(0, 20).saturating_mul(m.into()))
	}
	/// Storage: `TreasuryCouncil::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::ProposalOf` (r:1 w:0)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[1, 9]`.
	fn propose_execute(_b: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `100 + m * (20 ±0)`
		//  Estimated: `3566 + m * (20 ±0)`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(14_000_978, 3566)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(Weight::from_parts(0, 20).saturating_mul(m.into()))
	}
	/// Storage: `TreasuryCouncil::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::ProposalOf` (r:1 w:1)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::ProposalCount` (r:1 w:1)
	/// Proof: `TreasuryCouncil::ProposalCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Voting` (r:0 w:1)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[2, 9]`.
	/// The range of component `p` is `[1, 20]`.
	fn propose_proposed(b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `17 + m * (20 ±0) + p * (58 ±0)`
		//  Estimated: `3482 + m * (20 ±0) + p * (58 ±0)`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(18_629_622, 3482)
			// Standard Error: 1_198
			.saturating_add(Weight::from_parts(978, 0).saturating_mul(b.into()))
			// Standard Error: 64_460
			.saturating_add(Weight::from_parts(368_421, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 20).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 58).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncil::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Voting` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[5, 9]`.
	fn vote(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `668 + m * (40 ±0)`
		//  Estimated: `4133 + m * (40 ±0)`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(13_000_000, 4133)
			// Standard Error: 176_776
			.saturating_add(Weight::from_parts(500_000, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 40).saturating_mul(m.into()))
	}
	/// Storage: `TreasuryCouncil::Voting` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::ProposalOf` (r:0 w:1)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[4, 9]`.
	/// The range of component `p` is `[1, 20]`.
	fn close_early_disapproved(m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `210 + m * (40 ±0) + p * (55 ±0)`
		//  Estimated: `3676 + m * (40 ±0) + p * (55 ±0)`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(12_152_631, 3676)
			// Standard Error: 258_198
			.saturating_add(Weight::from_parts(600_000, 0).saturating_mul(m.into()))
			// Standard Error: 67_947
			.saturating_add(Weight::from_parts(447_368, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 40).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 55).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncil::Voting` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::ProposalOf` (r:1 w:1)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[4, 9]`.
	/// The range of component `p` is `[1, 20]`.
	fn close_early_approved(b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `134 + b * (1 ±0) + m * (40 ±0) + p * (78 ±0)`
		//  Estimated: `3599 + b * (1 ±0) + m * (40 ±0) + p * (79 ±0)`
		// Minimum execution time: 26_000_000 picoseconds.
		Weight::from_parts(20_661_386, 3599)
			// Standard Error: 1_080
			.saturating_add(Weight::from_parts(2_201, 0).saturating_mul(b.into()))
			// Standard Error: 220_794
			.saturating_add(Weight::from_parts(350_000, 0).saturating_mul(m.into()))
			// Standard Error: 58_103
			.saturating_add(Weight::from_parts(434_210, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 1).saturating_mul(b.into()))
			.saturating_add(Weight::from_parts(0, 40).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 79).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncil::Voting` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Prime` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::ProposalOf` (r:0 w:1)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[4, 9]`.
	/// The range of component `p` is `[1, 20]`.
	fn close_disapproved(m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `261 + m * (32 ±0) + p * (55 ±0)`
		//  Estimated: `3726 + m * (32 ±0) + p * (55 ±0)`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(18_589_473, 3726)
			// Standard Error: 258_198
			.saturating_add(Weight::from_parts(300_000, 0).saturating_mul(m.into()))
			// Standard Error: 67_947
			.saturating_add(Weight::from_parts(210_526, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 55).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncil::Voting` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Prime` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::ProposalOf` (r:1 w:1)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[4, 9]`.
	/// The range of component `p` is `[1, 20]`.
	fn close_approved(b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `152 + b * (1 ±0) + m * (40 ±0) + p * (78 ±0)`
		//  Estimated: `3617 + b * (1 ±0) + m * (40 ±0) + p * (79 ±0)`
		// Minimum execution time: 28_000_000 picoseconds.
		Weight::from_parts(29_948_161, 3617)
			// Standard Error: 220_794
			.saturating_add(Weight::from_parts(50_000, 0).saturating_mul(m.into()))
			// Standard Error: 58_103
			.saturating_add(Weight::from_parts(355_263, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 1).saturating_mul(b.into()))
			.saturating_add(Weight::from_parts(0, 40).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 79).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncil::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Voting` (r:0 w:1)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::ProposalOf` (r:0 w:1)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `p` is `[1, 20]`.
	fn disapprove_proposal(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `258 + p * (32 ±0)`
		//  Estimated: `1744 + p * (32 ±0)`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(14_605_263, 1744)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncil::ProposalOf` (r:1 w:1)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::CostOf` (r:1 w:0)
	/// Proof: `TreasuryCouncil::CostOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Voting` (r:0 w:1)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `d` is `[0, 1]`.
	/// The range of component `p` is `[1, 20]`.
	fn kill(d: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1305 + p * (55 ±0)`
		//  Estimated: `4771 + p * (55 ±0)`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(15_236_842, 4771)
			// Standard Error: 408_248
			.saturating_add(Weight::from_parts(500_000, 0).saturating_mul(d.into()))
			// Standard Error: 21_486
			.saturating_add(Weight::from_parts(263_157, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 55).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncil::ProposalOf` (r:1 w:0)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::CostOf` (r:1 w:0)
	/// Proof: `TreasuryCouncil::CostOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn release_proposal_cost() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `747`
		//  Estimated: `4212`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(11_000_000, 4212)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
}
