// Script to automate scraping raw bytecodes from a manually deployed network
// It will create a JSON file with the bytecodes of all contracts, addresses, storages, nonce
//
// Append comment to JSON that explains it's autogenerated and how to run this script
