/**
 * Test to validate that state-diff.json matches the expected checksum.
 *
 * This test ensures that state-diff.json is up-to-date with the current contracts.
 *
 * If this test fails, it means the contracts have changed and state-diff.json
 * needs to be regenerated by running: `bun generate:contracts`
 */

import { describe, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const STATE_DIFF_PATH = join(import.meta.dir, "../../contracts/deployments/state-diff.json");
const STATE_DIFF_CHECKSUM_PATH = join(
  import.meta.dir,
  "../../contracts/deployments/state-diff.checksum"
);

describe("State Diff Validation", () => {
  test("state-diff.json should match expected checksum", () => {
    if (!existsSync(STATE_DIFF_PATH)) {
      throw new Error(
        `state-diff.json not found at ${STATE_DIFF_PATH}. Run 'bun generate:contracts' to generate it.`
      );
    }

    if (!existsSync(STATE_DIFF_CHECKSUM_PATH)) {
      throw new Error(
        `state-diff.checksum not found at ${STATE_DIFF_CHECKSUM_PATH}. Run 'bun generate:contracts' to generate it.`
      );
    }

    const content = readFileSync(STATE_DIFF_PATH, "utf-8");
    const hash = createHash("sha256");
    hash.update(content);
    const actualChecksum = hash.digest("hex");

    const expectedChecksum = readFileSync(STATE_DIFF_CHECKSUM_PATH, "utf-8").trim();

    if (actualChecksum !== expectedChecksum) {
      throw new Error(
        "state-diff.json checksum mismatch!\n\n" +
          `Expected: ${expectedChecksum}\n` +
          `Actual:   ${actualChecksum}\n\n` +
          "This means the contracts have changed. Please run 'bun generate:contracts' to regenerate state-diff.json"
      );
    }

    expect(actualChecksum).toBe(expectedChecksum);
  });
});
